### ISSUE TITLE
Use in-place callbacks

### ISSUE THREAD

**Issue by lassepe** [CLeARoboticsLab/MixedComplementarityProblems.jl#13]
Currently, the code uses the out-of-place `SymbolicUtils.build_function` calls which causes extra allocations. It would be a good idea to allocate a buffer and write to it very round instead to keep the GC in check

**Comment by dfridovi** [comment]
Agreed. I saw how [ParametricMCPs](https://github.com/JuliaGameTheoreticPlanning/ParametricMCPs.jl/blob/main/src/parametric_problem.jl) does this, but the `SparseFunction` bit didn't quite make sense to me since I am not as familiar with the sparse matrix formatting details. I'd love to hop on a call and knock this out together sometime soon.
